import { pgTable, serial, varchar, text, timestamp, integer, boolean, decimal, jsonb, date, time } from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';

// ============================================
// BETTER AUTH TABLES (Generated by CLI)
// ============================================

export const users = pgTable("users", {
  id: varchar("id", { length: 255 }).primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  email: varchar("email", { length: 255 }).notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: varchar("image", { length: 500 }),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
  stripeCustomerId: varchar("stripe_customer_id", { length: 255 }),
  role: varchar("role", { length: 50 }).default("member").notNull(),
});

export const session = pgTable("session", {
  id: varchar("id", { length: 255 }).primaryKey(),
  expiresAt: timestamp("expires_at").notNull(),
  token: varchar("token", { length: 255 }).notNull().unique(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
  ipAddress: varchar("ip_address", { length: 255 }),
  userAgent: varchar("user_agent", { length: 500 }),
  userId: varchar("user_id", { length: 255 }).notNull().references(() => users.id, { onDelete: "cascade" }),
});

export const account = pgTable("account", {
  id: varchar("id", { length: 255 }).primaryKey(),
  accountId: varchar("account_id", { length: 255 }).notNull(),
  providerId: varchar("provider_id", { length: 255 }).notNull(),
  userId: varchar("user_id", { length: 255 }).notNull().references(() => users.id, { onDelete: "cascade" }),
  accessToken: varchar("access_token", { length: 500 }),
  refreshToken: varchar("refresh_token", { length: 500 }),
  idToken: text("id_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at"),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
  scope: varchar("scope", { length: 500 }),
  password: varchar("password", { length: 255 }),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const verification = pgTable("verification", {
  id: varchar("id", { length: 255 }).primaryKey(),
  identifier: varchar("identifier", { length: 255 }).notNull(),
  value: varchar("value", { length: 255 }).notNull(),
  expiresAt: timestamp("expires_at").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const subscription = pgTable("subscription", {
  id: varchar("id", { length: 255 }).primaryKey(),
  plan: varchar("plan", { length: 255 }).notNull(),
  referenceId: varchar("reference_id", { length: 255 }).notNull(),
  stripeCustomerId: varchar("stripe_customer_id", { length: 255 }),
  stripeSubscriptionId: varchar("stripe_subscription_id", { length: 255 }),
  status: varchar("status", { length: 50 }).default("incomplete"),
  periodStart: timestamp("period_start"),
  periodEnd: timestamp("period_end"),
  trialStart: timestamp("trial_start"),
  trialEnd: timestamp("trial_end"),
  cancelAtPeriodEnd: boolean("cancel_at_period_end").default(false),
  cancelAt: timestamp("cancel_at"),
  canceledAt: timestamp("canceled_at"),
  endedAt: timestamp("ended_at"),
  seats: integer("seats"),
});

// Better Auth Relations
export const usersRelations = relations(users, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(users, {
    fields: [session.userId],
    references: [users.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(users, {
    fields: [account.userId],
    references: [users.id],
  }),
}));

// ============================================
// APPLICATION TABLES
// ============================================

// Members table
export const members = pgTable('members', {
  id: serial('id').primaryKey(),
  userId: varchar('user_id', { length: 255 }).notNull().unique(),
  phone: varchar('phone', { length: 50 }),
  emergencyContact: varchar('emergency_contact', { length: 255 }),
  healthNotes: text('health_notes'),
  joinDate: timestamp('join_date').defaultNow(),
  status: varchar('status', { length: 50 }).default('active'),
  qrCode: varchar('qr_code', { length: 255 }),
  stripeCustomerId: varchar('stripe_customer_id', { length: 255 }),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

// Trainers table
export const trainers = pgTable('trainers', {
  id: serial('id').primaryKey(),
  userId: varchar('user_id', { length: 255 }).notNull().unique(),
  bio: text('bio'),
  specialization: varchar('specialization', { length: 255 }),
  certifications: text('certifications'),
  maxClients: integer('max_clients').default(20),
  hourlyRate: decimal('hourly_rate', { precision: 10, scale: 2 }),
  videoStorageQuota: integer('video_storage_quota').default(1073741824), // 1GB in bytes
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

// Subscription Plans
export const subscriptionPlans = pgTable('subscription_plans', {
  id: serial('id').primaryKey(),
  name: varchar('name', { length: 100 }).notNull(),
  description: text('description'),
  stripePriceId: varchar('stripe_price_id', { length: 255 }),
  stripeAnnualPriceId: varchar('stripe_annual_price_id', { length: 255 }),
  interval: varchar('interval', { length: 50 }).default('month'),
  price: decimal('price', { precision: 10, scale: 2 }),
  features: jsonb('features').default([]),
  isActive: boolean('is_active').default(true),
  createdAt: timestamp('created_at').defaultNow(),
});

// Member Subscriptions
export const memberSubscriptions = pgTable('member_subscriptions', {
  id: serial('id').primaryKey(),
  memberId: integer('member_id').references(() => members.id),
  stripeSubscriptionId: varchar('stripe_subscription_id', { length: 255 }),
  planId: integer('plan_id').references(() => subscriptionPlans.id),
  status: varchar('status', { length: 50 }).default('active'),
  currentPeriodStart: timestamp('current_period_start'),
  currentPeriodEnd: timestamp('current_period_end'),
  cancelAtPeriodEnd: boolean('cancel_at_period_end').default(false),
  canceledAt: timestamp('canceled_at'),
  endedAt: timestamp('ended_at'),
  trialStart: timestamp('trial_start'),
  trialEnd: timestamp('trial_end'),
  seats: integer('seats').default(1),
  createdAt: timestamp('created_at').defaultNow(),
});

// Attendance
export const attendance = pgTable('attendance', {
  id: serial('id').primaryKey(),
  memberId: integer('member_id').references(() => members.id),
  checkInTime: timestamp('check_in_time').defaultNow(),
  date: date('date').defaultNow(),
  method: varchar('method', { length: 50 }).default('qr_code'),
  createdAt: timestamp('created_at').defaultNow(),
});

// Exercise Library
export const exercises = pgTable('exercises', {
  id: serial('id').primaryKey(),
  name: varchar('name', { length: 255 }).notNull(),
  category: varchar('category', { length: 100 }),
  muscleGroup: varchar('muscle_group', { length: 100 }),
  description: text('description'),
  defaultVideoUrl: varchar('default_video_url', { length: 500 }),
  createdAt: timestamp('created_at').defaultNow(),
});

// Workout Plans
export const workoutPlans = pgTable('workout_plans', {
  id: serial('id').primaryKey(),
  trainerId: integer('trainer_id').references(() => trainers.id),
  memberId: integer('member_id').references(() => members.id),
  name: varchar('name', { length: 255 }).notNull(),
  description: text('description'),
  startDate: date('start_date'),
  endDate: date('end_date'),
  isActive: boolean('is_active').default(true),
  createdAt: timestamp('created_at').defaultNow(),
});

// Plan Exercises
export const planExercises = pgTable('plan_exercises', {
  id: serial('id').primaryKey(),
  planId: integer('plan_id').references(() => workoutPlans.id),
  exerciseId: integer('exercise_id').references(() => exercises.id),
  sets: integer('sets'),
  reps: varchar('reps', { length: 50 }),
  weight: decimal('weight', { precision: 10, scale: 2 }),
  restSeconds: integer('rest_seconds'),
  notes: text('notes'),
  orderIndex: integer('order_index').default(0),
  customVideoUrl: varchar('custom_video_url', { length: 500 }),
  customVideoBlobUrl: varchar('custom_video_blob_url', { length: 500 }),
  createdAt: timestamp('created_at').defaultNow(),
});

// Progress Tracking - Measurements
export const measurements = pgTable('measurements', {
  id: serial('id').primaryKey(),
  memberId: integer('member_id').references(() => members.id),
  date: date('date').notNull(),
  weight: decimal('weight', { precision: 5, scale: 2 }),
  bodyFat: decimal('body_fat', { precision: 5, scale: 2 }),
  chest: decimal('chest', { precision: 5, scale: 2 }),
  waist: decimal('waist', { precision: 5, scale: 2 }),
  hips: decimal('hips', { precision: 5, scale: 2 }),
  arms: decimal('arms', { precision: 5, scale: 2 }),
  thighs: decimal('thighs', { precision: 5, scale: 2 }),
  notes: text('notes'),
  createdAt: timestamp('created_at').defaultNow(),
});

// Progress Photos
export const progressPhotos = pgTable('progress_photos', {
  id: serial('id').primaryKey(),
  memberId: integer('member_id').references(() => members.id),
  date: date('date').notNull(),
  url: varchar('url', { length: 500 }),
  blobUrl: varchar('blob_url', { length: 500 }),
  type: varchar('type', { length: 50 }),
  notes: text('notes'),
  createdAt: timestamp('created_at').defaultNow(),
});

// Personal Records
export const personalRecords = pgTable('personal_records', {
  id: serial('id').primaryKey(),
  memberId: integer('member_id').references(() => members.id),
  exerciseName: varchar('exercise_name', { length: 255 }).notNull(),
  weight: decimal('weight', { precision: 10, scale: 2 }),
  reps: integer('reps'),
  date: date('date').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
});

// Achievements
export const achievements = pgTable('achievements', {
  id: serial('id').primaryKey(),
  name: varchar('name', { length: 255 }).notNull(),
  description: text('description'),
  icon: varchar('icon', { length: 255 }),
  criteriaType: varchar('criteria_type', { length: 100 }),
  criteriaValue: integer('criteria_value'),
  points: integer('points').default(0),
  createdAt: timestamp('created_at').defaultNow(),
});

// Member Achievements
export const memberAchievements = pgTable('member_achievements', {
  id: serial('id').primaryKey(),
  memberId: integer('member_id').references(() => members.id),
  achievementId: integer('achievement_id').references(() => achievements.id),
  earnedAt: timestamp('earned_at').defaultNow(),
});

// Classes
export const classes = pgTable('classes', {
  id: serial('id').primaryKey(),
  name: varchar('name', { length: 255 }).notNull(),
  trainerId: integer('trainer_id').references(() => trainers.id),
  maxCapacity: integer('max_capacity').default(20),
  durationMinutes: integer('duration_minutes').default(60),
  description: text('description'),
  color: varchar('color', { length: 50 }).default('#3b82f6'),
  createdAt: timestamp('created_at').defaultNow(),
});

// Class Schedules
export const classSchedules = pgTable('class_schedules', {
  id: serial('id').primaryKey(),
  classId: integer('class_id').references(() => classes.id),
  dayOfWeek: integer('day_of_week').notNull(), // 0-6 (Sunday-Saturday)
  startTime: time('start_time').notNull(),
  room: varchar('room', { length: 100 }),
  createdAt: timestamp('created_at').defaultNow(),
});

// Class Bookings
export const classBookings = pgTable('class_bookings', {
  id: serial('id').primaryKey(),
  scheduleId: integer('schedule_id').references(() => classSchedules.id),
  memberId: integer('member_id').references(() => members.id),
  bookingDate: date('booking_date').notNull(),
  status: varchar('status', { length: 50 }).default('confirmed'),
  createdAt: timestamp('created_at').defaultNow(),
});

// Equipment
export const equipment = pgTable('equipment', {
  id: serial('id').primaryKey(),
  name: varchar('name', { length: 255 }).notNull(),
  category: varchar('category', { length: 100 }),
  purchaseDate: date('purchase_date'),
  warrantyExpiry: date('warranty_expiry'),
  lastMaintenance: date('last_maintenance'),
  nextMaintenance: date('next_maintenance'),
  status: varchar('status', { length: 50 }).default('active'),
  qrCode: varchar('qr_code', { length: 255 }),
  createdAt: timestamp('created_at').defaultNow(),
});

// Equipment Maintenance
export const equipmentMaintenance = pgTable('equipment_maintenance', {
  id: serial('id').primaryKey(),
  equipmentId: integer('equipment_id').references(() => equipment.id),
  maintenanceDate: date('maintenance_date').notNull(),
  description: text('description'),
  cost: decimal('cost', { precision: 10, scale: 2 }),
  performedBy: varchar('performed_by', { length: 255 }),
  createdAt: timestamp('created_at').defaultNow(),
});

// Messages
export const messages = pgTable('messages', {
  id: serial('id').primaryKey(),
  senderId: varchar('sender_id', { length: 255 }).notNull(),
  receiverId: varchar('receiver_id', { length: 255 }).notNull(),
  content: text('content').notNull(),
  isRead: boolean('is_read').default(false),
  createdAt: timestamp('created_at').defaultNow(),
});

// Application Relations
export const membersRelations = relations(members, ({ many, one }) => ({
  user: one(users, {
    fields: [members.userId],
    references: [users.id],
  }),
  subscriptions: many(memberSubscriptions),
  attendance: many(attendance),
  workoutPlans: many(workoutPlans),
  measurements: many(measurements),
  progressPhotos: many(progressPhotos),
  personalRecords: many(personalRecords),
  achievements: many(memberAchievements),
  classBookings: many(classBookings),
}))

export const trainersRelations = relations(trainers, ({ many, one }) => ({
  user: one(users, {
    fields: [trainers.userId],
    references: [users.id],
  }),
  workoutPlans: many(workoutPlans),
  classes: many(classes),
}))

export const subscriptionPlansRelations = relations(subscriptionPlans, ({ many }) => ({
  subscriptions: many(memberSubscriptions),
}));

export const memberSubscriptionsRelations = relations(memberSubscriptions, ({ one }) => ({
  member: one(members, {
    fields: [memberSubscriptions.memberId],
    references: [members.id],
  }),
  plan: one(subscriptionPlans, {
    fields: [memberSubscriptions.planId],
    references: [subscriptionPlans.id],
  }),
}));

export const workoutPlansRelations = relations(workoutPlans, ({ one, many }) => ({
  trainer: one(trainers, {
    fields: [workoutPlans.trainerId],
    references: [trainers.id],
  }),
  member: one(members, {
    fields: [workoutPlans.memberId],
    references: [members.id],
  }),
  exercises: many(planExercises),
}));

export const exercisesRelations = relations(exercises, ({ many }) => ({
  planExercises: many(planExercises),
}));

export const planExercisesRelations = relations(planExercises, ({ one }) => ({
  plan: one(workoutPlans, {
    fields: [planExercises.planId],
    references: [workoutPlans.id],
  }),
  exercise: one(exercises, {
    fields: [planExercises.exerciseId],
    references: [exercises.id],
  }),
}));

export const classesRelations = relations(classes, ({ one, many }) => ({
  trainer: one(trainers, {
    fields: [classes.trainerId],
    references: [trainers.id],
  }),
  schedules: many(classSchedules),
}));

export const classSchedulesRelations = relations(classSchedules, ({ one, many }) => ({
  class: one(classes, {
    fields: [classSchedules.classId],
    references: [classes.id],
  }),
  bookings: many(classBookings),
}));

export const classBookingsRelations = relations(classBookings, ({ one }) => ({
  schedule: one(classSchedules, {
    fields: [classBookings.scheduleId],
    references: [classSchedules.id],
  }),
  member: one(members, {
    fields: [classBookings.memberId],
    references: [members.id],
  }),
}));

export const equipmentRelations = relations(equipment, ({ many }) => ({
  maintenance: many(equipmentMaintenance),
}));

export const equipmentMaintenanceRelations = relations(equipmentMaintenance, ({ one }) => ({
  equipment: one(equipment, {
    fields: [equipmentMaintenance.equipmentId],
    references: [equipment.id],
  }),
}));

export const achievementsRelations = relations(achievements, ({ many }) => ({
  memberAchievements: many(memberAchievements),
}));

export const memberAchievementsRelations = relations(memberAchievements, ({ one }) => ({
  member: one(members, {
    fields: [memberAchievements.memberId],
    references: [members.id],
  }),
  achievement: one(achievements, {
    fields: [memberAchievements.achievementId],
    references: [achievements.id],
  }),
}));

// Types
export type Member = typeof members.$inferSelect;
export type NewMember = typeof members.$inferInsert;
export type Trainer = typeof trainers.$inferSelect;
export type NewTrainer = typeof trainers.$inferInsert;
export type SubscriptionPlan = typeof subscriptionPlans.$inferSelect;
export type NewSubscriptionPlan = typeof subscriptionPlans.$inferInsert;
export type MemberSubscription = typeof memberSubscriptions.$inferSelect;
export type NewMemberSubscription = typeof memberSubscriptions.$inferInsert;
export type Attendance = typeof attendance.$inferSelect;
export type NewAttendance = typeof attendance.$inferInsert;
export type Exercise = typeof exercises.$inferSelect;
export type NewExercise = typeof exercises.$inferInsert;
export type WorkoutPlan = typeof workoutPlans.$inferSelect;
export type NewWorkoutPlan = typeof workoutPlans.$inferInsert;
export type PlanExercise = typeof planExercises.$inferSelect;
export type NewPlanExercise = typeof planExercises.$inferInsert;
export type Measurement = typeof measurements.$inferSelect;
export type NewMeasurement = typeof measurements.$inferInsert;
export type ProgressPhoto = typeof progressPhotos.$inferSelect;
export type NewProgressPhoto = typeof progressPhotos.$inferInsert;
export type PersonalRecord = typeof personalRecords.$inferSelect;
export type NewPersonalRecord = typeof personalRecords.$inferInsert;
export type Achievement = typeof achievements.$inferSelect;
export type NewAchievement = typeof achievements.$inferInsert;
export type MemberAchievement = typeof memberAchievements.$inferSelect;
export type NewMemberAchievement = typeof memberAchievements.$inferInsert;
export type Class = typeof classes.$inferSelect;
export type NewClass = typeof classes.$inferInsert;
export type ClassSchedule = typeof classSchedules.$inferSelect;
export type NewClassSchedule = typeof classSchedules.$inferInsert;
export type ClassBooking = typeof classBookings.$inferSelect;
export type NewClassBooking = typeof classBookings.$inferInsert;
export type Equipment = typeof equipment.$inferSelect;
export type NewEquipment = typeof equipment.$inferInsert;
export type EquipmentMaintenance = typeof equipmentMaintenance.$inferSelect;
export type NewEquipmentMaintenance = typeof equipmentMaintenance.$inferInsert;
export type Message = typeof messages.$inferSelect;
export type NewMessage = typeof messages.$inferInsert;
